### PR TITLE
Prevent CI from running on README/docs updates

### PR DESCRIPTION
**Pull request by elliotmatson**

### CODE REVIEW

**Comment by mrfaptastic** [comment]
I was wondering about this. Thank you for this. Great work!

**Comment by elliotmatson** [comment]
For sure! I've been looking at getting CI to test the S2 and S3, but for some reason ESPIDF with Arduino as a component won't recognize Serial as being defined anywhere with those 2 platforms

**Comment by mrfaptastic** [comment]
I shouldn't have any use of Serial in this library anymore.

**Comment by elliotmatson** [comment]
No it's not in the library, just in the PIO example. I could just define it out, but I can't reproduce it on the one ESP-IDF project I'm currently working on with an S3, so at this point I'm just trying to figure out what I'm missing

**Pull request merged**
