### PR TITLE
Add Hue Spectrum Example

### PR DESCRIPTION
**Pull request by Kouzeru**
...and to elaborate how the BCM correction works.

Anyway, seems I couldn't figure out how redefine `PIXEL_COLOUR_DEPTH_BITS` and to make it work for the example.

### CODE REVIEW

**Comment by mrfaptastic** [comment]
CI fails again, but I'll fix the use of max()

**Comment by mrfaptastic** [comment]
Ignore my last comment. All looks  good. Thanks for the example as well .Very cool.

**Comment by mrfaptastic** [comment]
Out of curosity will this brightness logic still work OK if people define PIXEL_COLOUR_DEPTH_BITS less than 8?

**Comment by mrfaptastic** [comment]
Will this brightness logic still work OK if people define PIXEL_COLOUR_DEPTH_BITS less than 8?

**Comment by Kouzeru** [comment]
> Will this brightness logic still work OK if people define PIXEL_COLOUR_DEPTH_BITS less than 8?

Yes, and the gradation bands is more sensible with the CIE1931 turned off.

**Comment by mrfaptastic** [comment]
Do you suggest the library define NO_CIE1931 (i.e. turn off CCIE1931) then the PIXEL_COLOUR_DEPTH_BITS  less than 8?

**Comment by mrfaptastic** [comment]
Do you suggest that the library define NO_CIE1931 (i.e. turn CIE1931 off) when PIXEL_COLOUR_DEPTH_BITS less than 8?

**Comment by Kouzeru** [comment]
> Do you suggest that the library define NO_CIE1931 (i.e. turn CIE1931 off) when PIXEL_COLOUR_DEPTH_BITS less than 8?
Um, I'm unsure, maybe not, or just probably never.

It's nice to have the gamma correction but, the LED requires it being 16 bitplanes in order to faithfully represent the whole RGB888. Having 8 bitplanes (which the library defaults to) is more fitting for representing the whole RGB444 or almost RGB565

**Comment by Kouzeru** [comment]
By the way, the last bitplane (bitplane 7) of the 8 bits being unrendered (which explains why there is no difference between 7-bit and 8-bit color depths) really bother me much, and im seeing flaws when looking some of each of the bitplanes.

**Comment by mrfaptastic** [comment]
Do you still get this issue when you compile the whole library with:

FORCE_COLOUR_DEPTH  

.. defined?

**Comment by mrfaptastic** [comment]
Basically the library does some stuff in the background to keep the refresh rate up at the expense of perceived colour depth: lsbMsbTransitionBit

Not sure how this will interact with the brightness code.

**Pull request merged**
