### PR TITLE
Add esp-idf standalone support

### PR DESCRIPTION
**Pull request by chegewara**
Added esp-idf standalone support, but tested only with esp-idf v5.0.
It should not break arduino support, but not tested yet.

### CODE REVIEW

**Review by mrfaptastic — APPROVED** [review]
Thanks for this.

**Comment by abrender** [comment]
@chegewara Thanks for adding this!

I tried to use this but kept running into `src/platforms/esp32s3/gdma_lcd_parallel16.hpp:34:10: fatal error: esp_lcd_panel_io.h: No such file or directory`

This is because the CMakeLists.txt file has `PRIV_REQUIRES ${arduino_build} ${esp_idf_build}` however per the [documentation](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/build-system.html#when-writing-a-component), `REQUIRES` "should be set to all components whose header files are #included from the public header files of this component.".    Because `esp_lcd_panel_io.h` is included in the public `gdma_lcd_parallel16.hpp` header it should use `REQUIRES` instead of `PRIV_REQUIRES`.

I think the same will apply to the `driver` component.

**Comment by chegewara** [comment]
Sorry, i should mention that. I tested with esp-idf v5.0, which is using new components manager and new components. Few of them are missing in v4.4.x, like esp_lcd.

**Comment by abrender** [comment]
I don't think the issue is with v4.4.x vs v5.   I think the issue is that the CMakeLists.txt file uses `PRIV_REQUIRES` instead of `REQUIRES`.

My project works if my `CMakeLists.txt` file has:
```
  REQUIRES esp_lcd ESP32-HUB75-MatrixPanel-I2S-DMA
```

But my project will not compile if it is missing `esp_lcd`:
```
  REQUIRES ESP32-HUB75-MatrixPanel-I2S-DMA
```

The solution is to update [this](https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-DMA/blob/642729b5f948bf8d66a5fbf4f435f6b44e932019/CMakeLists.txt#L16) to use `REQUIRES` instead of `PRIV_REQUIRES` so that users of this `ESP32-HUB75-MatrixPanel-I2S-DMA` component do not need to include `esp_lcd` themselves.

**Comment by chegewara** [comment]
Sure, that also may be the issue.
I tested with only one project which does not require esp_lcd.
I can change it of course.

**Comment by mrfaptastic** [comment]
I feel like a pull request is incoming 🙂

**Pull request merged**
