### PR TITLE
BCM accumulation correction

### LINKED ISSUE #373: Some a bit incorrect color and shade gradations
I'm putting some sort of image test to display some hue and value spectrum,
I got some noticeable color banding when using this driver:

I had deployed another technique to actually do the BCM properly, thus, displaying more faithful hue and value spectrum:

(with the cost of sacrificing 1/4 of the total brightness of course, due to limitation of my driver)

Here;s the code of the test image
```
  char t = millis()>>4;
  for(int x=0;x<128;x++)
    for(int y=0;y<64;y++)
      dma_display->drawPixelRGB888(x,y,
      (uint8_t)((max(min(cosf(2.f*PI*((x-t)/128.f+0.f/3.f))+0.5f,1.f),0.f)*((y+1.f)/64.f))*255.f),
      (uint8_t)((max(min(cosf(2.f*PI*((x-t)/128.f+1.f/3.f))+0.5f,1.f),0.f)*((y+1.f)/64.f))*255.f),
      (uint8_t)((max(min(cosf(2.f*PI*((x-t)/128.f+2.f/3.f))+0.5f,1.f),0.f)*((y+1.f)/64.f))*255.f)
      );
  ```

### PR DESCRIPTION
**Pull request by Kouzeru**
resolves #373 

before correction:

after correction:

### CODE REVIEW

**Comment by mrfaptastic** [comment]
This is magic. I don't quite understand how such a simple fix works, but thank you kindly!

**Comment by mrfaptastic** [comment]
Build seems to be failing now, can you check?

**Comment by Kouzeru** [comment]
image
That's odd, i didn't account it would compile in PlatformIO, should change the max() it into std::max() ?

**Comment by mrfaptastic** [comment]
Yep.

**Comment by Kouzeru** [comment]
Hold on. -- I'll include the new example hue-value-test for the bonus of this.

**Pull request merged**
