### PR TITLE
Add Github Actions tests for esp-idf

### PR DESCRIPTION
**Pull request by abrender**
This pull request adds two tests using the `esp-idf` framework:
  * A test with the Arduino GFX library (which requires the arduino-esp32 library & Arduino BusIO library)
  * A test without the Arduino GFX library, which can be compiled without any additional dependencies.

Having these tests helps prevent any future regressions that may break users of the `esp-idf` platform.

### CODE REVIEW

**Comment by abrender** [comment]
Examples of the passing actions can be seen here: https://github.com/abrender/ESP32-HUB75-MatrixPanel-DMA/actions

@mrfaptastic I'm not sure if there's something that you need to do to authorize the `espressif/esp-idf-ci-action@v1` action?

**Comment by abrender** [comment]
Woops, I see a temporary `.swp` file in the commit. I'll fox this when I'm back on my laptop tomorrow

**Comment by mrfaptastic** [comment]
We're not merging this anymore?

**Comment by abrender** [comment]
> We're not merging this anymore?

Sorry, I made a few changes (broke out https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-DMA/pull/459 into it's own pull request, removed some symlinks, added some README files, changed the workflow files a little bit) and figured it'd be cleanest to start with a new PR - https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-DMA/pull/460 - which you just merged. Thanks!

**Pull request closed without merging**
