### PR TITLE
Fix compilation fail with NO_GFX

### PR DESCRIPTION
**Pull request by Kouzeru**
and code cleaning up on the drawing routines involving orientations

### CODE REVIEW

**Comment by mrfaptastic** [comment]
This doesn't pass CI, your transform function refers to values that don't exist.

```
In file included from .pio/libdeps/esp32/ESP32 HUB75 LED MATRIX PANEL DMA Display/src/ESP32-HUB75-MatrixPanel-I2S-DMA.h:12,
                 from src/src/main.cpp:17:
.pio/libdeps/esp32/ESP32 HUB75 LED MATRIX PANEL DMA Display/src/platforms/platform_detect.hpp:58:19: note: #pragma message: Compiling for original ESP32 (released 2016)
   #pragma message "Compiling for original ESP32 (released 2016)"
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from src/src/main.cpp:17:
.pio/libdeps/esp32/ESP32 HUB75 LED MATRIX PANEL DMA Display/src/ESP32-HUB75-MatrixPanel-I2S-DMA.h: In member function 'virtual void MatrixPanel_I2S_DMA::drawPixel(int16_t, int16_t, uint16_t)':
.pio/libdeps/esp32/ESP32 HUB75 LED MATRIX PANEL DMA Display/src/ESP32-HUB75-MatrixPanel-I2S-DMA.h:822:11: error: 'rotation' was not declared in this scope
   switch (rotation) {
           ^~~~~~~~
.pio/libdeps/esp32/ESP32 HUB75 LED MATRIX PANEL DMA Display/src/ESP32-HUB75-MatrixPanel-I2S-DMA.h:822:11: note: suggested alternative: 'sigaction'
   switch (rotation) {
           ^~~~~~~~
           sigaction
.pio/libdeps/esp32/ESP32 HUB75 LED MATRIX PANEL DMA Display/src/ESP32-HUB75-MatrixPanel-I2S-DMA.h:824:36: error: '_height' was not declared in this scope
     case 1: updateMatrixDMABuffer( _height - 1 - y, x, r, g, b); break;
                                    ^~~~~~~
.pio/libdeps/esp32/ESP32 HUB75 LED MATRIX PANEL DMA Display/src/ESP32-HUB75-MatrixPanel-I2S-DMA.h:825:36: error: '_width' was not declared in this scope
     case 2: updateMatrixDMABuffer( _width - 1 - x, _height - 1 - y, r, g, b); break;
                                    ^~~~~~
.pio/libdeps/esp32/ESP32 HUB75 LED MATRIX PANEL DMA Display/src/ESP32-HUB75-MatrixPanel-I2S-DMA.h:825:36: note: suggested alternative: 'wcwidth'
     case 2: updateMatrixDMABuffer( _width - 1 - x, _height - 1 - y, r, g, b); break;

**Comment by Kouzeru** [comment]
Bruh no, that's false alarm, the CI compiles the old code, please merge this first

The error pointing to non-existing code on the PR

**Comment by mrfaptastic** [comment]
Ok. In @Kouzeru I trust.  😀

**Comment by mrfaptastic** [comment]
I should have never doubted. Passed CI with flying colours :-)

**Comment by Kouzeru** [comment]
Pretty cool :3

**Pull request merged**
